# docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    networks:
      - transletez-moi-api
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - transletez-moi-api
    depends_on:
      - api

  db:
    container_name: transletez-moi-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: transletez-moi
      POSTGRES_USER: transletez-moi
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transletez-moi-api

volumes:
  postgres_data:

networks:
  transletez-moi-api:
    driver: bridge